# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


#### Q2 : Afficher la version de numpy et la configuration 

In [2]:
!which numpy

'which' n'est pas reconnu en tant que commande interne
ou externe, un programme ex‚cutable ou un fichier de commandes.


#### Q3 : Créer un vecteur nul de taille 10

In [3]:
a = np.zeros(10); 
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [4]:
a[3]=1; a

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [5]:
z = np.linspace(10, 50, 50)
z

array([10.        , 10.81632653, 11.63265306, 12.44897959, 13.26530612,
       14.08163265, 14.89795918, 15.71428571, 16.53061224, 17.34693878,
       18.16326531, 18.97959184, 19.79591837, 20.6122449 , 21.42857143,
       22.24489796, 23.06122449, 23.87755102, 24.69387755, 25.51020408,
       26.32653061, 27.14285714, 27.95918367, 28.7755102 , 29.59183673,
       30.40816327, 31.2244898 , 32.04081633, 32.85714286, 33.67346939,
       34.48979592, 35.30612245, 36.12244898, 36.93877551, 37.75510204,
       38.57142857, 39.3877551 , 40.20408163, 41.02040816, 41.83673469,
       42.65306122, 43.46938776, 44.28571429, 45.10204082, 45.91836735,
       46.73469388, 47.55102041, 48.36734694, 49.18367347, 50.        ])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [6]:
z2 = np.flip(z)
z2

array([50.        , 49.18367347, 48.36734694, 47.55102041, 46.73469388,
       45.91836735, 45.10204082, 44.28571429, 43.46938776, 42.65306122,
       41.83673469, 41.02040816, 40.20408163, 39.3877551 , 38.57142857,
       37.75510204, 36.93877551, 36.12244898, 35.30612245, 34.48979592,
       33.67346939, 32.85714286, 32.04081633, 31.2244898 , 30.40816327,
       29.59183673, 28.7755102 , 27.95918367, 27.14285714, 26.32653061,
       25.51020408, 24.69387755, 23.87755102, 23.06122449, 22.24489796,
       21.42857143, 20.6122449 , 19.79591837, 18.97959184, 18.16326531,
       17.34693878, 16.53061224, 15.71428571, 14.89795918, 14.08163265,
       13.26530612, 12.44897959, 11.63265306, 10.81632653, 10.        ])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [7]:
m = np.linspace(0,8,9);
m.shape = (3,3);
m

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

#### Q8 : Créer une matrice identié 3x3 

In [8]:
mId = np.diag(np.ones([3]));
mId

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [57]:
mId = np.random.rand(3,3,3)
mId.dtype='int';
mId

array([[[ 1583863368,  1068561880,  1517377965,  1072570575,
          1132750011,  1071782255],
        [ 2111643194,  1072628145, -1130023114,  1071538907,
         -1751921176,  1068955365],
        [ 1037974752,  1069226189, -1194991564,  1070870978,
          -660259964,  1070509930]],

       [[ 2046362534,  1072193312,  -159771870,  1072592288,
         -1870733326,  1071679905],
        [ -544807232,  1069523285, -1956716434,  1072092803,
         -1345309068,  1070985452],
        [ -644510624,  1069947276, -1917854233,  1072227297,
           784053787,  1071868080]],

       [[ -573841304,  1070822314,   -97538334,  1071598228,
         -1460430876,  1071209725],
        [ -751114752,  1066278852,  -646704628,  1071261491,
         -1166341868,  1070194581],
        [ -105652352,  1072499570, -2096025443,  1072344041,
         -1652553501,  1071906457]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [10]:
mId = np.random.rand(10,10);

In [11]:
mId.max()

0.9624071001408154

In [12]:
mId.min()

0.019678469759766726

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [13]:
m = np.diag(np.ones(5)); 
m
m[1,0] = 1
m[2,1] = 2
m[3,2] = 3
m[4,3] = 4;
m

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 2., 1., 0., 0.],
       [0., 0., 3., 1., 0.],
       [0., 0., 0., 4., 1.]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [14]:
ls = np.random.rand(5); 
ls
ls.sum()

2.2324859436902287

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [15]:
ls = np.random.rand(5);
ls
ls.mean()

0.432176186537364

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [32]:
ls = [x for x in range(11)]
    a = np.size(ls);
a

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [34]:
tab = np.random.rand(10,10);
tab

array([[0.83291771, 0.41041635, 0.95318544, 0.76595736, 0.64918601,
        0.63028605, 0.4463034 , 0.14715136, 0.0656188 , 0.65540158],
       [0.51815875, 0.21376796, 0.27136732, 0.87927402, 0.90378638,
        0.30809202, 0.80334993, 0.56308912, 0.59913459, 0.57566542],
       [0.37408722, 0.92728781, 0.33496599, 0.97403733, 0.9328691 ,
        0.89035113, 0.67761394, 0.18280451, 0.41456956, 0.02722169],
       [0.82477816, 0.50109085, 0.80041852, 0.47953994, 0.04491165,
        0.79266166, 0.75813812, 0.72444237, 0.55559234, 0.453838  ],
       [0.89862796, 0.04238099, 0.43507097, 0.52403705, 0.3240069 ,
        0.29635665, 0.04883301, 0.73715012, 0.73506189, 0.29721073],
       [0.68726025, 0.78699999, 0.27610115, 0.0540383 , 0.48836961,
        0.06219875, 0.74981765, 0.77683427, 0.5308578 , 0.85604438],
       [0.68964898, 0.67476126, 0.61352244, 0.23119962, 0.30605287,
        0.11149762, 0.39256515, 0.96729494, 0.25218237, 0.93775439],
       [0.69316796, 0.76066904, 0.6898773

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [46]:
tabB = np.random.rand(1,5);
for i in range len(tabA)
    if tabA.size() = tabB.size()
        if tabA[i]=tabB[i]
            print ("True")
        else if 
            print ("False")
#tabA,tabB


SyntaxError: invalid syntax (<ipython-input-46-18e5e0672287>, line 3)

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [49]:
tab = np.random.rand(1,10); 
tab.dtype='int32';
tab

array([[-1252593241,  1071914452,  1409101892,  1069865224,  1967155402,
         1071441344,   885810569,  1072533552, -1902668893,  1072547744,
         -804655626,  1072197926, -1876620974,  1072282677, -2080837408,
         1067244610, -2101328028,  1070522931,   741682396,  1070100010]])

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [109]:
m = np.random.rand(5,5)
#m = np.array([[1,5],[5,1]])
mX = m - m.mean()
mX = mX / m.std();

m,mX

(array([[0.96072536, 0.44739785, 0.61459364, 0.54279804, 0.21984638],
        [0.55431631, 0.20088887, 0.03418583, 0.16499385, 0.67310586],
        [0.37116077, 0.72986624, 0.40083149, 0.14364816, 0.80639502],
        [0.73885013, 0.65031631, 0.59094531, 0.08896191, 0.68426604],
        [0.1434991 , 0.32326975, 0.23609089, 0.82644444, 0.39198074]]),
 array([[ 1.93688304, -0.05501296,  0.59376706,  0.3151742 , -0.93799482],
        [ 0.35986925, -1.01155678, -1.65842475, -1.1508424 ,  0.82081558],
        [-0.35084037,  1.04106635, -0.23570725, -1.2336714 ,  1.33802564],
        [ 1.07592708,  0.73238391,  0.502003  , -1.44587377,  0.86412108],
        [-1.23424981, -0.53667482, -0.87496026,  1.4158246 , -0.27005137]]))

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [107]:
m2 = np.random.rand(2,1)
m2.dtype='int'
mT = np.transpose(m2);
m2,mT

(array([[ 1506268565,  1072011140],
        [-1101048574,  1070631077]]),
 array([[ 1506268565, -1101048574],
        [ 1072011140,  1070631077]]))

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [90]:
input array
x = np.array([[ 1., 2., 3.], [ 4., 5., 6.], [ 7., 8., 9.]])
random boolean mask for which values will be changed

mask = np.random.randint(0,2,size=x.shape).astype(np.bool)
random matrix the same shape of your data

r = np.random.rand(*x.shape)*np.max(x)
use your mask to replace values in your input array
x[mask] = r[mask]

print(x)

SyntaxError: invalid syntax (<ipython-input-90-4fb8026c12fa>, line 2)

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)

In [112]:
m1 = np.random.rand(5,5,3);
m2 = np.random.rand(5,5)
m3 = ()
m1,m2,m3

(array([[[0.03925609, 0.76420398, 0.10638442],
         [0.12313134, 0.53214382, 0.71201712],
         [0.8908105 , 0.91470815, 0.59276433],
         [0.20077699, 0.28899808, 0.23936698],
         [0.97030541, 0.32428689, 0.37315469]],
 
        [[0.07315146, 0.93745483, 0.29107901],
         [0.44546272, 0.78363184, 0.53766058],
         [0.38568993, 0.77500295, 0.21852063],
         [0.97448333, 0.39663932, 0.06988743],
         [0.00866986, 0.83129275, 0.936742  ]],
 
        [[0.26346488, 0.37965966, 0.49713984],
         [0.97552611, 0.53717392, 0.15240672],
         [0.33661592, 0.91552876, 0.25475946],
         [0.6090092 , 0.08847876, 0.16889701],
         [0.55811532, 0.38887268, 0.78056192]],
 
        [[0.60426578, 0.76594097, 0.47110184],
         [0.28892162, 0.36909302, 0.12127743],
         [0.26617981, 0.56106069, 0.77011086],
         [0.50811525, 0.89537353, 0.93935423],
         [0.1147133 , 0.55333216, 0.13424542]],
 
        [[0.63986895, 0.88469846, 0.9860628 ],
 