# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
pip install numpy

#### Q2 : Afficher la version de numpy et la configuration 

In [ ]:
!which numpy

#### Q3 : Créer un vecteur nul de taille 10

In [15]:
a = np.zeros(10); 
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [16]:
a[3]=1; a

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [27]:
z = np.linspace(10, 50, 50)
z

array([10.        , 10.81632653, 11.63265306, 12.44897959, 13.26530612,
       14.08163265, 14.89795918, 15.71428571, 16.53061224, 17.34693878,
       18.16326531, 18.97959184, 19.79591837, 20.6122449 , 21.42857143,
       22.24489796, 23.06122449, 23.87755102, 24.69387755, 25.51020408,
       26.32653061, 27.14285714, 27.95918367, 28.7755102 , 29.59183673,
       30.40816327, 31.2244898 , 32.04081633, 32.85714286, 33.67346939,
       34.48979592, 35.30612245, 36.12244898, 36.93877551, 37.75510204,
       38.57142857, 39.3877551 , 40.20408163, 41.02040816, 41.83673469,
       42.65306122, 43.46938776, 44.28571429, 45.10204082, 45.91836735,
       46.73469388, 47.55102041, 48.36734694, 49.18367347, 50.        ])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [32]:
z2 = np.flip(z)
z2

array([50.        , 49.18367347, 48.36734694, 47.55102041, 46.73469388,
       45.91836735, 45.10204082, 44.28571429, 43.46938776, 42.65306122,
       41.83673469, 41.02040816, 40.20408163, 39.3877551 , 38.57142857,
       37.75510204, 36.93877551, 36.12244898, 35.30612245, 34.48979592,
       33.67346939, 32.85714286, 32.04081633, 31.2244898 , 30.40816327,
       29.59183673, 28.7755102 , 27.95918367, 27.14285714, 26.32653061,
       25.51020408, 24.69387755, 23.87755102, 23.06122449, 22.24489796,
       21.42857143, 20.6122449 , 19.79591837, 18.97959184, 18.16326531,
       17.34693878, 16.53061224, 15.71428571, 14.89795918, 14.08163265,
       13.26530612, 12.44897959, 11.63265306, 10.81632653, 10.        ])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [58]:
m = np.linspace(0,8,9);
m.shape = (3,3);
m

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

#### Q8 : Créer une matrice identié 3x3 

In [59]:
mId = np.diag(np.ones([3]));
mId

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [62]:
mId = np.random.rand(3,3,3)
mId

array([[[0.1529091 , 0.74843112, 0.38181211],
        [0.4667608 , 0.70653611, 0.28239535],
        [0.97195231, 0.51938071, 0.91570391]],

       [[0.45479345, 0.28215179, 0.32385419],
        [0.92875427, 0.85083934, 0.14365645],
        [0.96208122, 0.79697376, 0.86414238]],

       [[0.34029763, 0.498942  , 0.72958416],
        [0.94270777, 0.75853887, 0.21522305],
        [0.48500785, 0.80787874, 0.64243005]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [85]:
mId = np.random.rand(10,10);

In [86]:
mId.max()

0.9962179138405644

In [87]:
mId.min()

0.02097621868689492

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [9]:
m = np.diag(np.ones(5)); 
m
m[1,0] = 1
m[2,1] = 2
m[3,2] = 3
m[4,3] = 4;
m

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [0., 2., 1., 0., 0.],
       [0., 0., 3., 1., 0.],
       [0., 0., 0., 4., 1.]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [10]:
ls = np.random.rand(5); 
ls
ls.sum()

2.4660252052785627

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [11]:
ls = np.random.rand(5);
ls
ls.mean()

0.442556180783674

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)