## 1) NumPy

In [5]:
pip install numpy

In [6]:
!which python3

'which' n'est pas reconnu en tant que commande interne
ou externe, un programme ex‚cutable ou un fichier de commandes.


In [7]:
import numpy as np

In [3]:
l = [i for i in range{}]

SyntaxError: invalid syntax (<ipython-input-3-1be411b27b99>, line 1)

In [9]:
ar = np.array{l}

SyntaxError: invalid syntax (<ipython-input-9-adf6ba73471f>, line 1)

In [ ]:
ar

In [ ]:
ar.min()

In [ ]:
ar.max()

In [ ]:
ar.mean() #moyenne

In [ ]:
ar.std() #ecart type

In [10]:
ar.dtype() #datatype

NameError: name 'ar' is not defined

In [11]:
ex = list{[1,2,3,'s']}

SyntaxError: invalid syntax (<ipython-input-11-0d2e6dca176c>, line 1)

In [12]:
np.array(ex)

NameError: name 'ex' is not defined

In [1]:
m = np.array([[1,2],[3,4]])

In [14]:
m[0][1] = 9

2

In [15]:
m.shape 

(2, 2)

In [22]:
m2 = np.array([1,2,3,4,5], ndmin=2); m2

array([[1, 2, 3, 4, 5]])

In [23]:
m2.shape

(1, 5)

In [25]:
m2.shape(5,1)

TypeError: 'tuple' object is not callable

In [28]:
m2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [33]:
b = np.linspace(0, 2, 4) # 0--> nb depart , 2 --> nb arrivée , 4--> nb de valeurs

In [34]:
b**2 # chaque element est mis au carré / 0 et 2

array([0.        , 0.44444444, 1.77777778, 4.        ])

In [35]:
np.arrange(24)

AttributeError: module 'numpy' has no attribute 'arrange'

In [36]:
c = np.arrange(24).reshape(2,3,4); c

AttributeError: module 'numpy' has no attribute 'arrange'

In [37]:
c.shape

NameError: name 'c' is not defined

In [38]:
c.ndim

NameError: name 'c' is not defined

In [41]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])

### Exercices  /Cours

In [42]:
#lignes 2 et 3 et colonnes 1 et 2
ar[1:2,0:2]

array([[4, 5]])

In [43]:
#juste la 2eme ligne et un tableau à 1 dimension
ar[1,:]

array([4, 5, 6])

In [44]:
#la derniere colonne
ar[:,-1]

array([3, 6, 9])

In [45]:
s = "personne ecoute ce que je raconte"

In [46]:
s[0:9]

'personne '

In [48]:
ar==2

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [49]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
1,B

(1,
 array([[2, 0],
        [3, 4]]))

In [51]:
A+B #surcharge d'opérateur

array([[3, 1],
       [3, 5]])

In [ ]:
a = np.array([[1,2],[3,4]])

In [ ]:
a.argmax() #position avec l'argument maximum

In [52]:
b = np.array([1,7,2,8,3]

SyntaxError: unexpected EOF while parsing (<ipython-input-52-8503c9bf0698>, line 1)

In [53]:
sum(b) #fonction python

4.0

In [54]:
b.sum(axis=0) #colonne

4.0

In [55]:
b.sum(axis=1) #ligne

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
np.array([1,2,3,4]).cumsum()

In [56]:
np.arrange(10) #numpy array

AttributeError: module 'numpy' has no attribute 'arrange'

In [57]:
np.title(3,8);

AttributeError: module 'numpy' has no attribute 'title'

In [ ]:
z = npzeros((2,4)); z

In [4]:
z.dtype

NameError: name 'z' is not defined

In [63]:
6*z

NameError: name 'z' is not defined

In [62]:
np.ones((2,4), dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [61]:
np.diag(np.array([1,4]))

array([[1, 0],
       [0, 4]])